
const bikesArray = [
    {
      "id": 1,
      "productName": "Шосейний велосипед BraveWheel BT 28 inch",
      "productPrice": 15934,
      "productImageUrl": "./bikes/bike_1_white.webp",
      "productPageUrl": "bike_1_white",
      "amount": 0,
      "discount": 0,
      "humanHeight": [170,180],
      "wheelLength": 29,
    }, 
    {
      "id": 2,
      "productName": "Міський велосипед BraveWheel MI 29 inch",
      "productPrice": 10774,
      "productImageUrl": "./bikes/bike_2_orange.webp",
      "productPageUrl": "bike_2_orange",
      "amount": 0,
      "discount": 25,
      "humanHeight": [170,180],
      "wheelLength": 26,
    },
    {
      "id": 3, 
      "productName": "Гірський велосипед BraveWheel BR 28 inch",
      "productPrice": 17854,
      "productImageUrl": "./bikes/bike_3_gray.webp",
      "productPageUrl": "bike_3_gray",
      "amount": 0,
      "discount": 20,
      "humanHeight": [170,180],
      "wheelLength": 28,
    },
    {
      "id": 4,
      "productName": "Електро велосипед BraveWheel EV 26 inch",
      "productPrice": 29963,
      "productImageUrl": "./bikes/bike_4_electro.webp",
      "productPageUrl": "/bike_4_electro",
      "amount": 0,
      "discount": 5,
      "humanHeight": [160,170],
      "wheelLength": 28,
    },
    {
      "id": 5,
      "productName": "Шосейний велосипед BraveWheel BT 28 inch",
      "productPrice": 15934,
      "productImageUrl": "./bikes/bike_1_white.webp",
      "productPageUrl": "bike_1_white",
      "amount": 0,
      "discount": 50,
      "humanHeight": [170,180],
      "wheelLength": 29,
    }
  ]

  export default bikesArray;
